import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import FormImg from '../public/form.png'
import { useFormik } from 'formik'
import * as Yup from 'yup'
import { useRouter } from 'next/router'
import { motion as m } from 'framer-motion'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  const formik = useFormik({
    initialValues: {
      name: '',
      email: '',
      country: 'India',
      terms: '',
    },

    // Validation Form
    validationSchema: Yup.object({
      name: Yup.string().max(20, 'Name must be less than 20 characters')
        .min(3, 'Min length must be 3')
        .required('Name is required'),
      email: Yup.string().max(20, 'Email must be less than 20 characters')
        .email('Invalid email address')
        .required('Email is required'),
      terms: Yup.array().required('Terms must be Accepted'),
    }),

    // on submit
    onSubmit: (values) => {
      console.log(values);
      // NExt page with values
      router.push({ 'pathname': '/success', query: values });
    }
  })
  console.log(formik.errors)
  return (
    <m.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className=' absolute w-full'
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>

      </Head>
      <main className=' h-screen flex items-center justify-center'>
        <form
          onSubmit={formik.handleSubmit}
          className=' bg-white flex rounded-lg w-1/2'>
          <div className=' flex-1 text-gray-700 p-20'>
            <h1 className=' text-3xl pb-2'>
              Lets Get Started
            </h1>
            <p className=' text-lg text-gray-500'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur, at?
            </p>
            <div className=' mt-6'>
              <div className=' pb-4'>
                <label htmlFor="name" className={`block text-sm pb-2${formik.touched.name && formik.errors.name ? ' text-red-400' : ''}`}>
                  {formik.touched.name && formik.errors.name ? formik.errors.name : 'Name'}
                </label>
                <input
                  type="text"
                  value={formik.values.name}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  name='name'
                  placeholder='Jhon Doe'
                  className=' border-2 border-gray-500 p-2 rounded-md w-1/2'
                />
              </div>
              <div className=' pb-4'>
                <label htmlFor="email" className={`block text-sm pb-2 ${formik.touched.email && formik.errors.email ? ' text-red-400' : ""}`}>
                  {formik.touched.email && formik.errors.email ? formik.errors.email : 'Email'}
                </label>
                <input
                  type="email"
                  name='email'
                  value={formik.values.email}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  placeholder='Jhondoe@123.com'
                  className=' border-2 border-gray-500 p-2 rounded-md w-1/2'
                />
              </div>
              <div className=' pb-4'>
                <label htmlFor="email" className='block text-sm pb-2'>
                  Country
                </label>
                <select
                  value={formik.values.country}
                  onChange={formik.handleChange}
                  name='country'
                  className=' border-2 border-gray-500 p-2 rounded-md w-1/2'
                >
                  <option value="India">India</option>
                  <option value="US">US</option>
                  <option value="UK">UK</option>
                </select>
              </div>
              <div className=' pb-4'>
                <label htmlFor="email" className={`block text-sm pb-2${formik.touched.terms && formik.errors.terms ? ' text-red-400' : ""}`}>
                  {formik.touched.terms && formik.errors.terms ? formik.errors.terms : 'Terms and Conditions'}
                </label>
                <div className=' flex items-center gap-2'>
                  <input
                    type="checkbox"
                    name="terms"
                    // value={formik.values.terms}
                    value='Checked'
                    onChange={formik.handleChange}
                    onBlur={formik.handleBlur}
                    id=""
                    // value='checked'
                    className=' h-5 w-5' />
                  <p className=' text-sm text-gray-500'>
                    I agree to the terms and conditions
                  </p>
                </div>
              </div>
              <button
                type='submit'
                className=' bg-teal-500 text-sm text-white py-3 mt-6 rounded-lg w-full'
              >
                Start Learning
              </button>
            </div>
          </div>
          <div className=' flex-1 relative'>
            <Image src={FormImg} fill className=' object-cover rounded-lg' alt='Form img' />
          </div>
        </form>
      </main>
    </m.div>
  )
}
